// Generated by gencpp from file pp_msgs/MotionPlanningPlugin.msg
// DO NOT EDIT!


#ifndef PP_MSGS_MESSAGE_MOTIONPLANNINGPLUGIN_H
#define PP_MSGS_MESSAGE_MOTIONPLANNINGPLUGIN_H

#include <ros/service_traits.h>


#include <pp_msgs/MotionPlanningPluginRequest.h>
#include <pp_msgs/MotionPlanningPluginResponse.h>


namespace pp_msgs
{

struct MotionPlanningPlugin
{

typedef MotionPlanningPluginRequest Request;
typedef MotionPlanningPluginResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MotionPlanningPlugin
} // namespace pp_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pp_msgs::MotionPlanningPlugin > {
  static const char* value()
  {
    return "1fb7f778734b213306e1e32481d2f6bf";
  }

  static const char* value(const ::pp_msgs::MotionPlanningPlugin&) { return value(); }
};

template<>
struct DataType< ::pp_msgs::MotionPlanningPlugin > {
  static const char* value()
  {
    return "pp_msgs/MotionPlanningPlugin";
  }

  static const char* value(const ::pp_msgs::MotionPlanningPlugin&) { return value(); }
};


// service_traits::MD5Sum< ::pp_msgs::MotionPlanningPluginRequest> should match
// service_traits::MD5Sum< ::pp_msgs::MotionPlanningPlugin >
template<>
struct MD5Sum< ::pp_msgs::MotionPlanningPluginRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pp_msgs::MotionPlanningPlugin >::value();
  }
  static const char* value(const ::pp_msgs::MotionPlanningPluginRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pp_msgs::MotionPlanningPluginRequest> should match
// service_traits::DataType< ::pp_msgs::MotionPlanningPlugin >
template<>
struct DataType< ::pp_msgs::MotionPlanningPluginRequest>
{
  static const char* value()
  {
    return DataType< ::pp_msgs::MotionPlanningPlugin >::value();
  }
  static const char* value(const ::pp_msgs::MotionPlanningPluginRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pp_msgs::MotionPlanningPluginResponse> should match
// service_traits::MD5Sum< ::pp_msgs::MotionPlanningPlugin >
template<>
struct MD5Sum< ::pp_msgs::MotionPlanningPluginResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pp_msgs::MotionPlanningPlugin >::value();
  }
  static const char* value(const ::pp_msgs::MotionPlanningPluginResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pp_msgs::MotionPlanningPluginResponse> should match
// service_traits::DataType< ::pp_msgs::MotionPlanningPlugin >
template<>
struct DataType< ::pp_msgs::MotionPlanningPluginResponse>
{
  static const char* value()
  {
    return DataType< ::pp_msgs::MotionPlanningPlugin >::value();
  }
  static const char* value(const ::pp_msgs::MotionPlanningPluginResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PP_MSGS_MESSAGE_MOTIONPLANNINGPLUGIN_H
